title: JLRoofing
email: jlroofs@gmail.com
baseurl: "/"
url: "https://jlroofs.github.io"
description: JLRoofing
show-downloads: false
theme: theme: jekyll-theme-architect
timezone: America/Chicago
permalink: /archives/:year/:month/:day/:title:output_ext
github_username: jlroofs
